name: ArmSC

on: push

jobs: 
  build: 
    runs-on: ubuntu-latest 

    steps: 
      - uses: actions/checkout@v2 
      - name: Build image 
        run: make 
      - name: Run image 
        run: make run 
      - name: Run tests 
        run: make test_core 
